/* 
 * ARTIK Cloud API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using CLOUD.Artik.Client;
using CLOUD.Artik.Api;
using CLOUD.Artik.Model;

namespace CLOUD.Artik.Test
{
    /// <summary>
    ///  Class for testing DeviceTypesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DeviceTypesApiTests
    {
        private DeviceTypesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DeviceTypesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeviceTypesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DeviceTypesApi
            //Assert.IsInstanceOfType(typeof(DeviceTypesApi), instance, "instance is a DeviceTypesApi");
        }

        
        /// <summary>
        /// Test GetAvailableManifestVersions
        /// </summary>
        [Test]
        public void GetAvailableManifestVersionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string deviceTypeId = null;
            //var response = instance.GetAvailableManifestVersions(deviceTypeId);
            //Assert.IsInstanceOf<ManifestVersionsEnvelope> (response, "response is ManifestVersionsEnvelope");
        }
        
        /// <summary>
        /// Test GetDeviceType
        /// </summary>
        [Test]
        public void GetDeviceTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string deviceTypeId = null;
            //var response = instance.GetDeviceType(deviceTypeId);
            //Assert.IsInstanceOf<DeviceTypeEnvelope> (response, "response is DeviceTypeEnvelope");
        }
        
        /// <summary>
        /// Test GetDeviceTypes
        /// </summary>
        [Test]
        public void GetDeviceTypesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //int? offset = null;
            //int? count = null;
            //string tags = null;
            //var response = instance.GetDeviceTypes(name, offset, count, tags);
            //Assert.IsInstanceOf<DeviceTypesEnvelope> (response, "response is DeviceTypesEnvelope");
        }
        
        /// <summary>
        /// Test GetLatestManifestProperties
        /// </summary>
        [Test]
        public void GetLatestManifestPropertiesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string deviceTypeId = null;
            //var response = instance.GetLatestManifestProperties(deviceTypeId);
            //Assert.IsInstanceOf<ManifestPropertiesEnvelope> (response, "response is ManifestPropertiesEnvelope");
        }
        
        /// <summary>
        /// Test GetManifestProperties
        /// </summary>
        [Test]
        public void GetManifestPropertiesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string deviceTypeId = null;
            //string version = null;
            //var response = instance.GetManifestProperties(deviceTypeId, version);
            //Assert.IsInstanceOf<ManifestPropertiesEnvelope> (response, "response is ManifestPropertiesEnvelope");
        }
        
    }

}
