/* 
 * ARTIK Cloud API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using CLOUD.Artik.Api;
using NUnit.Framework;

namespace CLOUD.Artik.Test
{
    /// <summary>
    ///     Class for testing RegistrationsApi
    /// </summary>
    /// <remarks>
    ///     This file is automatically generated by Swagger Codegen.
    ///     Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RegistrationsApiTests
    {
        private RegistrationsApi instance;

        /// <summary>
        ///     Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RegistrationsApi();
        }

        /// <summary>
        ///     Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }
        
        /// <summary>
        ///     Test ConfirmUser
        /// </summary>
        [Test]
        public void ConfirmUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DeviceRegConfirmUserRequest registrationInfo = null;
            //var response = instance.ConfirmUser(registrationInfo);
            //Assert.IsInstanceOf<DeviceRegConfirmUserResponseEnvelope> (response, "response is DeviceRegConfirmUserResponseEnvelope");
        }

        /// <summary>
        ///     Test GetRequestStatusForUser
        /// </summary>
        [Test]
        public void GetRequestStatusForUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string requestId = null;
            //var response = instance.GetRequestStatusForUser(requestId);
            //Assert.IsInstanceOf<DeviceRegStatusResponseEnvelope> (response, "response is DeviceRegStatusResponseEnvelope");
        }

        /// <summary>
        ///     Test UnregisterDevice
        /// </summary>
        [Test]
        public void UnregisterDeviceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string deviceId = null;
            //var response = instance.UnregisterDevice(deviceId);
            //Assert.IsInstanceOf<UnregisterDeviceResponseEnvelope> (response, "response is UnregisterDeviceResponseEnvelope");
        }
    }
}