/* 
 * ARTIK Cloud API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using CLOUD.Artik.Client;
using CLOUD.Artik.Model;

namespace CLOUD.Artik.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDevicesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Add Device
        /// </summary>
        /// <remarks>
        /// Create a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="device">Device to be added to the user</param>
        /// <returns>DeviceEnvelope</returns>
        DeviceEnvelope AddDevice (Device device);

        /// <summary>
        /// Add Device
        /// </summary>
        /// <remarks>
        /// Create a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="device">Device to be added to the user</param>
        /// <returns>ApiResponse of DeviceEnvelope</returns>
        ApiResponse<DeviceEnvelope> AddDeviceWithHttpInfo (Device device);
        /// <summary>
        /// Delete Device
        /// </summary>
        /// <remarks>
        /// Deletes a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>DeviceEnvelope</returns>
        DeviceEnvelope DeleteDevice (string deviceId);

        /// <summary>
        /// Delete Device
        /// </summary>
        /// <remarks>
        /// Deletes a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>ApiResponse of DeviceEnvelope</returns>
        ApiResponse<DeviceEnvelope> DeleteDeviceWithHttpInfo (string deviceId);
        /// <summary>
        /// Delete Device Token
        /// </summary>
        /// <remarks>
        /// Deletes a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>DeviceTokenEnvelope</returns>
        DeviceTokenEnvelope DeleteDeviceToken (string deviceId);

        /// <summary>
        /// Delete Device Token
        /// </summary>
        /// <remarks>
        /// Deletes a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>ApiResponse of DeviceTokenEnvelope</returns>
        ApiResponse<DeviceTokenEnvelope> DeleteDeviceTokenWithHttpInfo (string deviceId);
        /// <summary>
        /// Get Device
        /// </summary>
        /// <remarks>
        /// Retrieves a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>DeviceEnvelope</returns>
        DeviceEnvelope GetDevice (string deviceId);

        /// <summary>
        /// Get Device
        /// </summary>
        /// <remarks>
        /// Retrieves a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>ApiResponse of DeviceEnvelope</returns>
        ApiResponse<DeviceEnvelope> GetDeviceWithHttpInfo (string deviceId);
        /// <summary>
        /// Get device presence information
        /// </summary>
        /// <remarks>
        /// Return the presence status of the given device along with the time it was last seen
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">Device ID.</param>
        /// <returns>PresenceEnvelope</returns>
        PresenceEnvelope GetDevicePresence (string deviceId);

        /// <summary>
        /// Get device presence information
        /// </summary>
        /// <remarks>
        /// Return the presence status of the given device along with the time it was last seen
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">Device ID.</param>
        /// <returns>ApiResponse of PresenceEnvelope</returns>
        ApiResponse<PresenceEnvelope> GetDevicePresenceWithHttpInfo (string deviceId);
        /// <summary>
        /// Get Device Token
        /// </summary>
        /// <remarks>
        /// Retrieves a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>DeviceTokenEnvelope</returns>
        DeviceTokenEnvelope GetDeviceToken (string deviceId);

        /// <summary>
        /// Get Device Token
        /// </summary>
        /// <remarks>
        /// Retrieves a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>ApiResponse of DeviceTokenEnvelope</returns>
        ApiResponse<DeviceTokenEnvelope> GetDeviceTokenWithHttpInfo (string deviceId);
        /// <summary>
        /// Update Device
        /// </summary>
        /// <remarks>
        /// Updates a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <param name="device">Device to be updated</param>
        /// <returns>DeviceEnvelope</returns>
        DeviceEnvelope UpdateDevice (string deviceId, Device device);

        /// <summary>
        /// Update Device
        /// </summary>
        /// <remarks>
        /// Updates a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <param name="device">Device to be updated</param>
        /// <returns>ApiResponse of DeviceEnvelope</returns>
        ApiResponse<DeviceEnvelope> UpdateDeviceWithHttpInfo (string deviceId, Device device);
        /// <summary>
        /// Update Device Token
        /// </summary>
        /// <remarks>
        /// Updates a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>DeviceTokenEnvelope</returns>
        DeviceTokenEnvelope UpdateDeviceToken (string deviceId);

        /// <summary>
        /// Update Device Token
        /// </summary>
        /// <remarks>
        /// Updates a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>ApiResponse of DeviceTokenEnvelope</returns>
        ApiResponse<DeviceTokenEnvelope> UpdateDeviceTokenWithHttpInfo (string deviceId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Add Device
        /// </summary>
        /// <remarks>
        /// Create a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="device">Device to be added to the user</param>
        /// <returns>Task of DeviceEnvelope</returns>
        System.Threading.Tasks.Task<DeviceEnvelope> AddDeviceAsync (Device device);

        /// <summary>
        /// Add Device
        /// </summary>
        /// <remarks>
        /// Create a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="device">Device to be added to the user</param>
        /// <returns>Task of ApiResponse (DeviceEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeviceEnvelope>> AddDeviceAsyncWithHttpInfo (Device device);
        /// <summary>
        /// Delete Device
        /// </summary>
        /// <remarks>
        /// Deletes a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of DeviceEnvelope</returns>
        System.Threading.Tasks.Task<DeviceEnvelope> DeleteDeviceAsync (string deviceId);

        /// <summary>
        /// Delete Device
        /// </summary>
        /// <remarks>
        /// Deletes a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of ApiResponse (DeviceEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeviceEnvelope>> DeleteDeviceAsyncWithHttpInfo (string deviceId);
        /// <summary>
        /// Delete Device Token
        /// </summary>
        /// <remarks>
        /// Deletes a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of DeviceTokenEnvelope</returns>
        System.Threading.Tasks.Task<DeviceTokenEnvelope> DeleteDeviceTokenAsync (string deviceId);

        /// <summary>
        /// Delete Device Token
        /// </summary>
        /// <remarks>
        /// Deletes a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of ApiResponse (DeviceTokenEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeviceTokenEnvelope>> DeleteDeviceTokenAsyncWithHttpInfo (string deviceId);
        /// <summary>
        /// Get Device
        /// </summary>
        /// <remarks>
        /// Retrieves a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of DeviceEnvelope</returns>
        System.Threading.Tasks.Task<DeviceEnvelope> GetDeviceAsync (string deviceId);

        /// <summary>
        /// Get Device
        /// </summary>
        /// <remarks>
        /// Retrieves a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of ApiResponse (DeviceEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeviceEnvelope>> GetDeviceAsyncWithHttpInfo (string deviceId);
        /// <summary>
        /// Get device presence information
        /// </summary>
        /// <remarks>
        /// Return the presence status of the given device along with the time it was last seen
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">Device ID.</param>
        /// <returns>Task of PresenceEnvelope</returns>
        System.Threading.Tasks.Task<PresenceEnvelope> GetDevicePresenceAsync (string deviceId);

        /// <summary>
        /// Get device presence information
        /// </summary>
        /// <remarks>
        /// Return the presence status of the given device along with the time it was last seen
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">Device ID.</param>
        /// <returns>Task of ApiResponse (PresenceEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<PresenceEnvelope>> GetDevicePresenceAsyncWithHttpInfo (string deviceId);
        /// <summary>
        /// Get Device Token
        /// </summary>
        /// <remarks>
        /// Retrieves a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of DeviceTokenEnvelope</returns>
        System.Threading.Tasks.Task<DeviceTokenEnvelope> GetDeviceTokenAsync (string deviceId);

        /// <summary>
        /// Get Device Token
        /// </summary>
        /// <remarks>
        /// Retrieves a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of ApiResponse (DeviceTokenEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeviceTokenEnvelope>> GetDeviceTokenAsyncWithHttpInfo (string deviceId);
        /// <summary>
        /// Update Device
        /// </summary>
        /// <remarks>
        /// Updates a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <param name="device">Device to be updated</param>
        /// <returns>Task of DeviceEnvelope</returns>
        System.Threading.Tasks.Task<DeviceEnvelope> UpdateDeviceAsync (string deviceId, Device device);

        /// <summary>
        /// Update Device
        /// </summary>
        /// <remarks>
        /// Updates a device
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <param name="device">Device to be updated</param>
        /// <returns>Task of ApiResponse (DeviceEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeviceEnvelope>> UpdateDeviceAsyncWithHttpInfo (string deviceId, Device device);
        /// <summary>
        /// Update Device Token
        /// </summary>
        /// <remarks>
        /// Updates a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of DeviceTokenEnvelope</returns>
        System.Threading.Tasks.Task<DeviceTokenEnvelope> UpdateDeviceTokenAsync (string deviceId);

        /// <summary>
        /// Update Device Token
        /// </summary>
        /// <remarks>
        /// Updates a device&#39;s token
        /// </remarks>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of ApiResponse (DeviceTokenEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeviceTokenEnvelope>> UpdateDeviceTokenAsyncWithHttpInfo (string deviceId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DevicesApi : IDevicesApi
    {
        private CLOUD.Artik.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DevicesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DevicesApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = CLOUD.Artik.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DevicesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DevicesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = CLOUD.Artik.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CLOUD.Artik.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Add Device Create a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="device">Device to be added to the user</param>
        /// <returns>DeviceEnvelope</returns>
        public DeviceEnvelope AddDevice (Device device)
        {
             ApiResponse<DeviceEnvelope> localVarResponse = AddDeviceWithHttpInfo(device);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Add Device Create a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="device">Device to be added to the user</param>
        /// <returns>ApiResponse of DeviceEnvelope</returns>
        public ApiResponse< DeviceEnvelope > AddDeviceWithHttpInfo (Device device)
        {
            // verify the required parameter 'device' is set
            if (device == null)
                throw new ApiException(400, "Missing required parameter 'device' when calling DevicesApi->AddDevice");

            var localVarPath = "/devices";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (device != null && device.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(device); // http body (model) parameter
            }
            else
            {
                localVarPostBody = device; // byte array
            }

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddDevice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceEnvelope)));
            
        }

        /// <summary>
        /// Add Device Create a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="device">Device to be added to the user</param>
        /// <returns>Task of DeviceEnvelope</returns>
        public async System.Threading.Tasks.Task<DeviceEnvelope> AddDeviceAsync (Device device)
        {
             ApiResponse<DeviceEnvelope> localVarResponse = await AddDeviceAsyncWithHttpInfo(device);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Add Device Create a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="device">Device to be added to the user</param>
        /// <returns>Task of ApiResponse (DeviceEnvelope)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DeviceEnvelope>> AddDeviceAsyncWithHttpInfo (Device device)
        {
            // verify the required parameter 'device' is set
            if (device == null)
                throw new ApiException(400, "Missing required parameter 'device' when calling DevicesApi->AddDevice");

            var localVarPath = "/devices";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (device != null && device.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(device); // http body (model) parameter
            }
            else
            {
                localVarPostBody = device; // byte array
            }

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddDevice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceEnvelope)));
            
        }

        /// <summary>
        /// Delete Device Deletes a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>DeviceEnvelope</returns>
        public DeviceEnvelope DeleteDevice (string deviceId)
        {
             ApiResponse<DeviceEnvelope> localVarResponse = DeleteDeviceWithHttpInfo(deviceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Device Deletes a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>ApiResponse of DeviceEnvelope</returns>
        public ApiResponse< DeviceEnvelope > DeleteDeviceWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->DeleteDevice");

            var localVarPath = "/devices/{deviceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteDevice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceEnvelope)));
            
        }

        /// <summary>
        /// Delete Device Deletes a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of DeviceEnvelope</returns>
        public async System.Threading.Tasks.Task<DeviceEnvelope> DeleteDeviceAsync (string deviceId)
        {
             ApiResponse<DeviceEnvelope> localVarResponse = await DeleteDeviceAsyncWithHttpInfo(deviceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete Device Deletes a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of ApiResponse (DeviceEnvelope)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DeviceEnvelope>> DeleteDeviceAsyncWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->DeleteDevice");

            var localVarPath = "/devices/{deviceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteDevice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceEnvelope)));
            
        }

        /// <summary>
        /// Delete Device Token Deletes a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>DeviceTokenEnvelope</returns>
        public DeviceTokenEnvelope DeleteDeviceToken (string deviceId)
        {
             ApiResponse<DeviceTokenEnvelope> localVarResponse = DeleteDeviceTokenWithHttpInfo(deviceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Device Token Deletes a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>ApiResponse of DeviceTokenEnvelope</returns>
        public ApiResponse< DeviceTokenEnvelope > DeleteDeviceTokenWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->DeleteDeviceToken");

            var localVarPath = "/devices/{deviceId}/tokens";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteDeviceToken", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceTokenEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceTokenEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceTokenEnvelope)));
            
        }

        /// <summary>
        /// Delete Device Token Deletes a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of DeviceTokenEnvelope</returns>
        public async System.Threading.Tasks.Task<DeviceTokenEnvelope> DeleteDeviceTokenAsync (string deviceId)
        {
             ApiResponse<DeviceTokenEnvelope> localVarResponse = await DeleteDeviceTokenAsyncWithHttpInfo(deviceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete Device Token Deletes a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of ApiResponse (DeviceTokenEnvelope)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DeviceTokenEnvelope>> DeleteDeviceTokenAsyncWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->DeleteDeviceToken");

            var localVarPath = "/devices/{deviceId}/tokens";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteDeviceToken", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceTokenEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceTokenEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceTokenEnvelope)));
            
        }

        /// <summary>
        /// Get Device Retrieves a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>DeviceEnvelope</returns>
        public DeviceEnvelope GetDevice (string deviceId)
        {
             ApiResponse<DeviceEnvelope> localVarResponse = GetDeviceWithHttpInfo(deviceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Device Retrieves a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>ApiResponse of DeviceEnvelope</returns>
        public ApiResponse< DeviceEnvelope > GetDeviceWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->GetDevice");

            var localVarPath = "/devices/{deviceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDevice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceEnvelope)));
            
        }

        /// <summary>
        /// Get Device Retrieves a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of DeviceEnvelope</returns>
        public async System.Threading.Tasks.Task<DeviceEnvelope> GetDeviceAsync (string deviceId)
        {
             ApiResponse<DeviceEnvelope> localVarResponse = await GetDeviceAsyncWithHttpInfo(deviceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Device Retrieves a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of ApiResponse (DeviceEnvelope)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DeviceEnvelope>> GetDeviceAsyncWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->GetDevice");

            var localVarPath = "/devices/{deviceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDevice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceEnvelope)));
            
        }

        /// <summary>
        /// Get device presence information Return the presence status of the given device along with the time it was last seen
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">Device ID.</param>
        /// <returns>PresenceEnvelope</returns>
        public PresenceEnvelope GetDevicePresence (string deviceId)
        {
             ApiResponse<PresenceEnvelope> localVarResponse = GetDevicePresenceWithHttpInfo(deviceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get device presence information Return the presence status of the given device along with the time it was last seen
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">Device ID.</param>
        /// <returns>ApiResponse of PresenceEnvelope</returns>
        public ApiResponse< PresenceEnvelope > GetDevicePresenceWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->GetDevicePresence");

            var localVarPath = "/devices/{deviceId}/presence";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDevicePresence", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PresenceEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PresenceEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PresenceEnvelope)));
            
        }

        /// <summary>
        /// Get device presence information Return the presence status of the given device along with the time it was last seen
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">Device ID.</param>
        /// <returns>Task of PresenceEnvelope</returns>
        public async System.Threading.Tasks.Task<PresenceEnvelope> GetDevicePresenceAsync (string deviceId)
        {
             ApiResponse<PresenceEnvelope> localVarResponse = await GetDevicePresenceAsyncWithHttpInfo(deviceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get device presence information Return the presence status of the given device along with the time it was last seen
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">Device ID.</param>
        /// <returns>Task of ApiResponse (PresenceEnvelope)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PresenceEnvelope>> GetDevicePresenceAsyncWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->GetDevicePresence");

            var localVarPath = "/devices/{deviceId}/presence";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDevicePresence", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PresenceEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PresenceEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PresenceEnvelope)));
            
        }

        /// <summary>
        /// Get Device Token Retrieves a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>DeviceTokenEnvelope</returns>
        public DeviceTokenEnvelope GetDeviceToken (string deviceId)
        {
             ApiResponse<DeviceTokenEnvelope> localVarResponse = GetDeviceTokenWithHttpInfo(deviceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Device Token Retrieves a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>ApiResponse of DeviceTokenEnvelope</returns>
        public ApiResponse< DeviceTokenEnvelope > GetDeviceTokenWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->GetDeviceToken");

            var localVarPath = "/devices/{deviceId}/tokens";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDeviceToken", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceTokenEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceTokenEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceTokenEnvelope)));
            
        }

        /// <summary>
        /// Get Device Token Retrieves a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of DeviceTokenEnvelope</returns>
        public async System.Threading.Tasks.Task<DeviceTokenEnvelope> GetDeviceTokenAsync (string deviceId)
        {
             ApiResponse<DeviceTokenEnvelope> localVarResponse = await GetDeviceTokenAsyncWithHttpInfo(deviceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Device Token Retrieves a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of ApiResponse (DeviceTokenEnvelope)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DeviceTokenEnvelope>> GetDeviceTokenAsyncWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->GetDeviceToken");

            var localVarPath = "/devices/{deviceId}/tokens";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDeviceToken", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceTokenEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceTokenEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceTokenEnvelope)));
            
        }

        /// <summary>
        /// Update Device Updates a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <param name="device">Device to be updated</param>
        /// <returns>DeviceEnvelope</returns>
        public DeviceEnvelope UpdateDevice (string deviceId, Device device)
        {
             ApiResponse<DeviceEnvelope> localVarResponse = UpdateDeviceWithHttpInfo(deviceId, device);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update Device Updates a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <param name="device">Device to be updated</param>
        /// <returns>ApiResponse of DeviceEnvelope</returns>
        public ApiResponse< DeviceEnvelope > UpdateDeviceWithHttpInfo (string deviceId, Device device)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->UpdateDevice");
            // verify the required parameter 'device' is set
            if (device == null)
                throw new ApiException(400, "Missing required parameter 'device' when calling DevicesApi->UpdateDevice");

            var localVarPath = "/devices/{deviceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter
            if (device != null && device.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(device); // http body (model) parameter
            }
            else
            {
                localVarPostBody = device; // byte array
            }

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateDevice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceEnvelope)));
            
        }

        /// <summary>
        /// Update Device Updates a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <param name="device">Device to be updated</param>
        /// <returns>Task of DeviceEnvelope</returns>
        public async System.Threading.Tasks.Task<DeviceEnvelope> UpdateDeviceAsync (string deviceId, Device device)
        {
             ApiResponse<DeviceEnvelope> localVarResponse = await UpdateDeviceAsyncWithHttpInfo(deviceId, device);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update Device Updates a device
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <param name="device">Device to be updated</param>
        /// <returns>Task of ApiResponse (DeviceEnvelope)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DeviceEnvelope>> UpdateDeviceAsyncWithHttpInfo (string deviceId, Device device)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->UpdateDevice");
            // verify the required parameter 'device' is set
            if (device == null)
                throw new ApiException(400, "Missing required parameter 'device' when calling DevicesApi->UpdateDevice");

            var localVarPath = "/devices/{deviceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter
            if (device != null && device.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(device); // http body (model) parameter
            }
            else
            {
                localVarPostBody = device; // byte array
            }

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateDevice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceEnvelope)));
            
        }

        /// <summary>
        /// Update Device Token Updates a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>DeviceTokenEnvelope</returns>
        public DeviceTokenEnvelope UpdateDeviceToken (string deviceId)
        {
             ApiResponse<DeviceTokenEnvelope> localVarResponse = UpdateDeviceTokenWithHttpInfo(deviceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update Device Token Updates a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>ApiResponse of DeviceTokenEnvelope</returns>
        public ApiResponse< DeviceTokenEnvelope > UpdateDeviceTokenWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->UpdateDeviceToken");

            var localVarPath = "/devices/{deviceId}/tokens";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "text/plain"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateDeviceToken", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceTokenEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceTokenEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceTokenEnvelope)));
            
        }

        /// <summary>
        /// Update Device Token Updates a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of DeviceTokenEnvelope</returns>
        public async System.Threading.Tasks.Task<DeviceTokenEnvelope> UpdateDeviceTokenAsync (string deviceId)
        {
             ApiResponse<DeviceTokenEnvelope> localVarResponse = await UpdateDeviceTokenAsyncWithHttpInfo(deviceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update Device Token Updates a device&#39;s token
        /// </summary>
        /// <exception cref="CLOUD.Artik.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">deviceId</param>
        /// <returns>Task of ApiResponse (DeviceTokenEnvelope)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DeviceTokenEnvelope>> UpdateDeviceTokenAsyncWithHttpInfo (string deviceId)
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->UpdateDeviceToken");

            var localVarPath = "/devices/{deviceId}/tokens";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "text/plain"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (deviceId != null) localVarPathParams.Add("deviceId", Configuration.ApiClient.ParameterToString(deviceId)); // path parameter

            // authentication (artikcloud_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateDeviceToken", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceTokenEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeviceTokenEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceTokenEnvelope)));
            
        }

    }
}
